version: '3'
services:
  flask_asilla2slack:
    build: ./flask2sla/
    volumes: 
      - "./flask2sla/src:/projects"
      - "./.env:/projects/.env"
      - "/tmp/videos:/tmp/videos"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "5050:5050"
    restart: always 
    container_name: flask2sla
    network_mode: "host"

  flask_asilla2airtable:
    build: ./flask2air
    volumes:
      - "./flask2air/src:/projects"
      - "./.env:/projects/.env"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "5051:5051"
    restart: always
    container_name: flask2air
    network_mode: "host"
  