version: '3'
services:
  flask_asilla2slack:
    build: .
    volumes: 
      - "./src:/projects"
      - "/tmp/videos:/tmp/videos"
    ports:
      - "5050:5050"
    restart: always 
    container_name: flask
